[versions]
# Library versions
minecraft = "26.1.2"

loader = "0.19.3"
fabric-api = "0.151.0+26.1.2"
fabric-kotlin = "1.13.9+kotlin.2.3.10"

rhino = "7c7c509668"
jackson-core = "3.2.0"
textarea = "3.6.3"
serialization = "1.11.0"

modmenu = "18.0.0-beta.1"

# Plugin Versions
kotlin = "2.4.0"
loom = "1.16-SNAPSHOT"
ksp = "2.3.9"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }

rhino = { module = "com.github.ChatTriggers:rhino", version.ref = "rhino" }
jackson-core = { module = "tools.jackson.core:jackson-core", version.ref = "jackson-core" }
textarea = { module = "com.fifesoft:rsyntaxtextarea", version.ref = "textarea" }
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[bundles]
fabric = ["fabric-loader", "fabric-api", "fabric-kotlin"]
included = ["rhino", "jackson-core", "textarea", "serialization"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
