[versions]
# Library versions
minecraft = "26.1.2"

loader = "0.19.3"
fabric-api = "0.155.2+26.1.2"
fabric-kotlin = "1.13.11+kotlin.2.3.21"

mapping-io = "0.8.0"
rhino = "7c7c509668"
jackson-core = "2.13.2"
textarea = "3.2.0"
serialization = "1.11.0"
koffee = "315bc11234"

universalcraft = "511"
elementa = "710"
vigilance = "314"

modmenu = "18.0.0"
devauth = "1.2.1"
dokka = "1.9.20"

# Plugin Versions
kotlin = "2.3.21"
loom = "1.17.19"
ksp = "2.3.11"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }

mapping-io = { module = "net.fabricmc:mapping-io", version.ref = "mapping-io" }
rhino = { module = "com.github.ChatTriggers:rhino", version.ref = "rhino" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson-core" }
textarea = { module = "com.fifesoft:rsyntaxtextarea", version.ref = "textarea" }
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
koffee = { module = "com.github.ChatTriggers:koffee", version.ref = "koffee" }

universalcraft = { module = "gg.essential:universalcraft-26.1-fabric", version.ref = "universalcraft" }
elementa = { module = "gg.essential:elementa", version.ref = "elementa" }
vigilance = { module = "gg.essential:vigilance", version.ref = "vigilance" }

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }
versioning = { module = "org.jetbrains.dokka:versioning-plugin", version.ref = "dokka" }

ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[bundles]
fabric = ["fabric-loader", "fabric-api", "fabric-kotlin"]
included = ["mapping-io", "rhino", "jackson-core", "textarea", "serialization", "koffee"]
essential = ["universalcraft", "elementa", "vigilance"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
